### PR TITLE
Release version

### PR DESCRIPTION
**Pull request by charvolant**
Updated to work with new name matching index

### CODE REVIEW

**Comment by ben3000** [comment]
I have code accomplishing some of this in the dev branch.

**Comment by charvolant** [comment]
Can we do a combined merge then? I'll make the version 0.17.0-SNAPSHOT, you merge your stuff and then we do a release?

**Comment by ben3000** [comment]
I was going to suggest that you just check your code into master, then I'll do a merge with dev and push my recent changes into master, but I think we may be saying the same thing?

**Comment by charvolant** [comment]
Yep. But I'll wind back the version number before doing so, so 0.17.0 (non-snapshot) can be updated.

**Pull request merged**
